// Loads the water supply dictionary generated by scripts/import-water-supply.mjs
import { normalize } from './search.js'

const baseUrl = `${import.meta.env.BASE_URL}water-supply/`

let indexPromise = null
const detailChunks = new Map()

function fetchJson(path) {
    return fetch(baseUrl + path).then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${path}`)
        return res.json()
    })
}

// Headwords of every entry: { id, ja, kana, en, lo, th, keys }
export function loadIndex() {
    if (!indexPromise) {
        indexPromise = fetchJson('index.json').then((list) =>
            list.map((entry) => ({
                ...entry,
                keys: [entry.ja, entry.kana, entry.en, entry.lo, entry.th].filter(Boolean).map(normalize),
            }))
        )
        indexPromise.catch(() => { indexPromise = null })
    }
    return indexPromise
}

// Descriptions and related terms of one entry: { desc: { ja, lo, th }, rel: { ja, lo, th } }
export function loadDetail(id) {
    const chunk = id.slice(0, 3)
    if (!detailChunks.has(chunk)) {
        const promise = fetchJson(`detail/${chunk}.json`)
        promise.catch(() => detailChunks.delete(chunk))
        detailChunks.set(chunk, promise)
    }
    return detailChunks.get(chunk).then((data) => data[id])
}
